var support = {A: "0: あ\n1: 𛀂<span class=\"std\">（安）</span>\n2: 𛀃<span class=\"std\">（愛）</span>\n3: 𛀄<span class=\"std\">（阿）</span>\n4: 𛀅<span class=\"std\">（惡）</span>\n", 
BA: "0: ば\n1: 𛂞゙\n2: 𛂟゙\n3: 𛂠゙\n4: 𛂡゙\n5: 𛂢゙\n6: 𛂣゙\n7: 𛂤゙\n8: 𛂥゙\n9: 𛂦゙\n10: 𛂧゙\n11: 𛂨゙\n", 
BE: "0: べ\n1: 𛂳゙\n2: 𛂴゙\n3: 𛂵゙\n4: 𛂶゙\n5: 𛂷゙\n6: 𛂸゙\n7: 𛂹゙\n", 
BI: "0: び\n1: 𛂩゙\n2: 𛂪゙\n3: 𛂫゙\n4: 𛂬゙\n5: 𛂭゙\n6: 𛂮゙\n7: 𛂯゙\n", 
BO: "0: ぼ\n1: 𛂺゙\n2: 𛂻゙\n3: 𛂼゙\n4: 𛂽゙\n5: 𛂾゙\n6: 𛂿゙\n7: 𛃀゙\n8: 𛃁゙\n", 
BU: "0: ぶ\n1: 𛂰゙\n2: 𛂱゙\n3: 𛂲゙\n", 
DA: "0: だ\n1: 𛁞゙\n2: 𛁟゙\n3: 𛁠゙\n4: 𛁡゙\n", 
DE: "0: で\n1: 𛁮゙\n2: 𛁯゙\n3: 𛁰゙\n4: 𛁱゙\n5: 𛁲゙\n6: 𛁳゙\n7: 𛁴゙\n8: 𛁵゙\n9: 𛁶゙\n10: 𛂎゙\n", 
DI: "0: ぢ\n1: 𛁢゙\n2: 𛁣゙\n3: 𛁤゙\n4: 𛁥゙\n5: 𛁦゙\n6: 𛁧゙\n7: 𛁨゙\n", 
DO: "0: ど\n1: 𛁭゙\n2: 𛁷゙\n3: 𛁸゙\n4: 𛁹゙\n5: 𛁺゙\n6: 𛁻゙\n7: 𛁼゙\n8: 𛁽゙\n", 
DU: "0: づ\n1: 𛁩゙\n2: 𛁪゙\n3: 𛁫゙\n4: 𛁬゙\n5: 𛁭゙\n", 
E: "0: え\n1: 𛀁<span class=\"std\">（江）</span>\n2: 𛀏<span class=\"std\">（盈）</span>\n3: 𛀐<span class=\"std\">（縁）</span>\n4: 𛀑<span class=\"std\">（衣）</span>\n5: 𛀒<span class=\"std\">（衣）</span>\n6: 𛀓<span class=\"std\">（要）</span>\n", 
GA: "0: が\n1: 𛀗゙\n2: 𛀘゙\n3: 𛀙゙\n4: 𛀚゙\n5: 𛀛゙\n6: 𛀜゙\n7: 𛀝゙\n8: 𛀞゙\n9: 𛀟゙\n10: 𛀠゙\n11: 𛀡゙\n12: 𛀢゙\n", 
GE: "0: げ\n1: 𛀢゙\n2: 𛀲゙\n3: 𛀳゙\n4: 𛀴゙\n5: 𛀵゙\n6: 𛀶゙\n7: 𛀷゙\n", 
GI: "0: ぎ\n1: 𛀣゙\n2: 𛀤゙\n3: 𛀥゙\n4: 𛀦゙\n5: 𛀧゙\n6: 𛀨゙\n7: 𛀩゙\n8: 𛀪゙\n9: 𛀻゙\n", 
GO: "0: ご\n1: 𛀸゙\n2: 𛀹゙\n3: 𛀺゙\n4: 𛀻゙\n5: 𛂘゙\n", 
GU: "0: ぐ\n1: 𛀫゙\n2: 𛀬゙\n3: 𛀭゙\n4: 𛀮゙\n5: 𛀯゙\n6: 𛀰゙\n7: 𛀱゙\n", 
HA: "0: は\n1: 𛂞<span class=\"std\">（八）</span>\n2: 𛂟<span class=\"std\">（半）</span>\n3: 𛂠<span class=\"std\">（婆）</span>\n4: 𛂡<span class=\"std\">（波）</span>\n5: 𛂢<span class=\"std\">（盤）</span>\n6: 𛂣<span class=\"std\">（盤）</span>\n7: 𛂤<span class=\"std\">（破）</span>\n8: 𛂥<span class=\"std\">（者）</span>\n9: 𛂦<span class=\"std\">（者）</span>\n10: 𛂧<span class=\"std\">（葉）</span>\n11: 𛂨<span class=\"std\">（頗）</span>\n", 
HE: "0: へ\n1: 𛂳<span class=\"std\">（倍）</span>\n2: 𛂴<span class=\"std\">（弊）</span>\n3: 𛂵<span class=\"std\">（弊）</span>\n4: 𛂶<span class=\"std\">（遍）</span>\n5: 𛂷<span class=\"std\">（邊）</span>\n6: 𛂸<span class=\"std\">（邊）</span>\n7: 𛂹<span class=\"std\">（部）</span>\n", 
HI: "0: ひ\n1: 𛂩<span class=\"std\">（悲）</span>\n2: 𛂪<span class=\"std\">（日）</span>\n3: 𛂫<span class=\"std\">（比）</span>\n4: 𛂬<span class=\"std\">（避）</span>\n5: 𛂭<span class=\"std\">（非）</span>\n6: 𛂮<span class=\"std\">（飛）</span>\n7: 𛂯<span class=\"std\">（飛）</span>\n", 
HO: "0: ほ\n1: 𛂺<span class=\"std\">（保）</span>\n2: 𛂻<span class=\"std\">（保）</span>\n3: 𛂼<span class=\"std\">（報）</span>\n4: 𛂽<span class=\"std\">（奉）</span>\n5: 𛂾<span class=\"std\">（寶）</span>\n6: 𛂿<span class=\"std\">（本）</span>\n7: 𛃀<span class=\"std\">（本）</span>\n8: 𛃁<span class=\"std\">（豐）</span>\n", 
HU: "0: ふ\n1: 𛂰<span class=\"std\">（不）</span>\n2: 𛂱<span class=\"std\">（婦）</span>\n3: 𛂲<span class=\"std\">（布）</span>\n", 
I: "0: い\n1: 𛀆<span class=\"std\">（以）</span>\n2: 𛀇<span class=\"std\">（伊）</span>\n3: 𛀈<span class=\"std\">（意）</span>\n4: 𛀉<span class=\"std\">（移）</span>\n", 
KA: "0: か\n1: 𛀗<span class=\"std\">（佳）</span>\n2: 𛀘<span class=\"std\">（加）</span>\n3: 𛀙<span class=\"std\">（可）</span>\n4: 𛀚<span class=\"std\">（可）</span>\n5: 𛀛<span class=\"std\">（嘉）</span>\n6: 𛀜<span class=\"std\">（我）</span>\n7: 𛀝<span class=\"std\">（歟）</span>\n8: 𛀞<span class=\"std\">（賀）</span>\n9: 𛀟<span class=\"std\">（閑）</span>\n10: 𛀠<span class=\"std\">（香）</span>\n11: 𛀡<span class=\"std\">（駕）</span>\n12: 𛀢<span class=\"std\">（家）</span>\n", 
KE: "0: け\n1: 𛀢<span class=\"std\">（家）</span>\n2: 𛀲<span class=\"std\">（介）</span>\n3: 𛀳<span class=\"std\">（介）</span>\n4: 𛀴<span class=\"std\">（希）</span>\n5: 𛀵<span class=\"std\">（氣）</span>\n6: 𛀶<span class=\"std\">（計）</span>\n7: 𛀷<span class=\"std\">（遣）</span>\n", 
KI: "0: き\n1: 𛀣<span class=\"std\">（喜）</span>\n2: 𛀤<span class=\"std\">（幾）</span>\n3: 𛀥<span class=\"std\">（幾）</span>\n4: 𛀦<span class=\"std\">（支）</span>\n5: 𛀧<span class=\"std\">（木）</span>\n6: 𛀨<span class=\"std\">（祈）</span>\n7: 𛀩<span class=\"std\">（貴）</span>\n8: 𛀪<span class=\"std\">（起）</span>\n9: 𛀻<span class=\"std\">（期）</span>\n", 
KO: "0: こ\n1: 𛀸<span class=\"std\">（古）</span>\n2: 𛀹<span class=\"std\">（故）</span>\n3: 𛀺<span class=\"std\">（許）</span>\n4: 𛀻<span class=\"std\">（期）</span>\n5: 𛂘<span class=\"std\">（子）</span>\n", 
KU: "0: く\n1: 𛀫<span class=\"std\">（久）</span>\n2: 𛀬<span class=\"std\">（久）</span>\n3: 𛀭<span class=\"std\">（九）</span>\n4: 𛀮<span class=\"std\">（供）</span>\n5: 𛀯<span class=\"std\">（倶）</span>\n6: 𛀰<span class=\"std\">（具）</span>\n7: 𛀱<span class=\"std\">（求）</span>\n", 
MA: "0: ま\n1: 𛃂<span class=\"std\">（万）</span>\n2: 𛃃<span class=\"std\">（末）</span>\n3: 𛃄<span class=\"std\">（末）</span>\n4: 𛃅<span class=\"std\">（滿）</span>\n5: 𛃆<span class=\"std\">（滿）</span>\n6: 𛃇<span class=\"std\">（萬）</span>\n7: 𛃈<span class=\"std\">（麻）</span>\n8: 𛃖<span class=\"std\">（馬）</span>\n", 
ME: "0: め\n1: 𛃔<span class=\"std\">（免）</span>\n2: 𛃕<span class=\"std\">（面）</span>\n3: 𛃖<span class=\"std\">（馬）</span>\n", 
MI: "0: み\n1: 𛃉<span class=\"std\">（三）</span>\n2: 𛃊<span class=\"std\">（微）</span>\n3: 𛃋<span class=\"std\">（美）</span>\n4: 𛃌<span class=\"std\">（美）</span>\n5: 𛃍<span class=\"std\">（美）</span>\n6: 𛃎<span class=\"std\">（見）</span>\n7: 𛃏<span class=\"std\">（身）</span>\n", 
MO: "0: も\n1: 𛃗<span class=\"std\">（母）</span>\n2: 𛃘<span class=\"std\">（毛）</span>\n3: 𛃙<span class=\"std\">（毛）</span>\n4: 𛃚<span class=\"std\">（毛）</span>\n5: 𛃛<span class=\"std\">（茂）</span>\n6: 𛃜<span class=\"std\">（裳）</span>\n7: 𛄝<span class=\"std\">（无）</span>\n8: 𛄞<span class=\"std\">（无）</span>\n", 
MU: "0: む\n1: 𛃐<span class=\"std\">（武）</span>\n2: 𛃑<span class=\"std\">（無）</span>\n3: 𛃒<span class=\"std\">（牟）</span>\n4: 𛃓<span class=\"std\">（舞）</span>\n5: 𛄝<span class=\"std\">（无）</span>\n6: 𛄞<span class=\"std\">（无）</span>\n", 
N: "0: ん\n1: 𛄝<span class=\"std\">（无）</span>\n2: 𛄞<span class=\"std\">（无）</span>\n", 
NA: "0: な\n1: 𛁾<span class=\"std\">（南）</span>\n2: 𛁿<span class=\"std\">（名）</span>\n3: 𛂀<span class=\"std\">（奈）</span>\n4: 𛂁<span class=\"std\">（奈）</span>\n5: 𛂂<span class=\"std\">（奈）</span>\n6: 𛂃<span class=\"std\">（菜）</span>\n7: 𛂄<span class=\"std\">（那）</span>\n8: 𛂅<span class=\"std\">（那）</span>\n9: 𛂆<span class=\"std\">（難）</span>\n", 
NE: "0: ね\n1: 𛂒<span class=\"std\">（年）</span>\n2: 𛂓<span class=\"std\">（年）</span>\n3: 𛂔<span class=\"std\">（年）</span>\n4: 𛂕<span class=\"std\">（根）</span>\n5: 𛂖<span class=\"std\">（熱）</span>\n6: 𛂗<span class=\"std\">（禰）</span>\n7: 𛂘<span class=\"std\">（子）</span>\n", 
NI: "0: に\n1: 𛂇<span class=\"std\">（丹）</span>\n2: 𛂈<span class=\"std\">（二）</span>\n3: 𛂉<span class=\"std\">（仁）</span>\n4: 𛂊<span class=\"std\">（兒）</span>\n5: 𛂋<span class=\"std\">（爾）</span>\n6: 𛂌<span class=\"std\">（爾）</span>\n7: 𛂍<span class=\"std\">（耳）</span>\n8: 𛂎<span class=\"std\">（而）</span>\n", 
NO: "0: の\n1: 𛂙<span class=\"std\">（乃）</span>\n2: 𛂚<span class=\"std\">（濃）</span>\n3: 𛂛<span class=\"std\">（能）</span>\n4: 𛂜<span class=\"std\">（能）</span>\n5: 𛂝<span class=\"std\">（農）</span>\n", 
NU: "0: ぬ\n1: 𛂏<span class=\"std\">（努）</span>\n2: 𛂐<span class=\"std\">（奴）</span>\n3: 𛂑<span class=\"std\">（怒）</span>\n", 
O: "0: お\n1: 𛀔<span class=\"std\">（於）</span>\n2: 𛀕<span class=\"std\">（於）</span>\n3: 𛀖<span class=\"std\">（隱）</span>\n", 
PA: "0: ぱ\n1: 𛂞゚\n2: 𛂟゚\n3: 𛂠゚\n4: 𛂡゚\n5: 𛂢゚\n6: 𛂣゚\n7: 𛂤゚\n8: 𛂥゚\n9: 𛂦゚\n10: 𛂧゚\n11: 𛂨゚\n", 
PE: "0: ぺ\n1: 𛂳゚\n2: 𛂴゚\n3: 𛂵゚\n4: 𛂶゚\n5: 𛂷゚\n6: 𛂸゚\n7: 𛂹゚\n", 
PI: "0: ぴ\n1: 𛂩゚\n2: 𛂪゚\n3: 𛂫゚\n4: 𛂬゚\n5: 𛂭゚\n6: 𛂮゚\n7: 𛂯゚\n", 
PO: "0: ぽ\n1: 𛂺゚\n2: 𛂻゚\n3: 𛂼゚\n4: 𛂽゚\n5: 𛂾゚\n6: 𛂿゚\n7: 𛃀゚\n8: 𛃁゚\n", 
PU: "0: ぷ\n1: 𛂰゚\n2: 𛂱゚\n3: 𛂲゚\n", 
RA: "0: ら\n1: 𛁽<span class=\"std\">（等）</span>\n2: 𛃭<span class=\"std\">（羅）</span>\n3: 𛃮<span class=\"std\">（良）</span>\n4: 𛃯<span class=\"std\">（良）</span>\n5: 𛃰<span class=\"std\">（良）</span>\n", 
RE: "0: れ\n1: 𛃾<span class=\"std\">（禮）</span>\n2: 𛃿<span class=\"std\">（禮）</span>\n3: 𛄀<span class=\"std\">（連）</span>\n4: 𛄁<span class=\"std\">（麗）</span>\n", 
RI: "0: り\n1: 𛃱<span class=\"std\">（利）</span>\n2: 𛃲<span class=\"std\">（利）</span>\n3: 𛃳<span class=\"std\">（李）</span>\n4: 𛃴<span class=\"std\">（梨）</span>\n5: 𛃵<span class=\"std\">（理）</span>\n6: 𛃶<span class=\"std\">（里）</span>\n7: 𛃷<span class=\"std\">（離）</span>\n", 
RO: "0: ろ\n1: 𛄂<span class=\"std\">（呂）</span>\n2: 𛄃<span class=\"std\">（呂）</span>\n3: 𛄄<span class=\"std\">（婁）</span>\n4: 𛄅<span class=\"std\">（樓）</span>\n5: 𛄆<span class=\"std\">（路）</span>\n6: 𛄇<span class=\"std\">（露）</span>\n", 
RU: "0: る\n1: 𛃸<span class=\"std\">（流）</span>\n2: 𛃹<span class=\"std\">（留）</span>\n3: 𛃺<span class=\"std\">（留）</span>\n4: 𛃻<span class=\"std\">（留）</span>\n5: 𛃼<span class=\"std\">（累）</span>\n6: 𛃽<span class=\"std\">（類）</span>\n", 
SA: "0: さ\n1: 𛀼<span class=\"std\">（乍）</span>\n2: 𛀽<span class=\"std\">（佐）</span>\n3: 𛀾<span class=\"std\">（佐）</span>\n4: 𛀿<span class=\"std\">（左）</span>\n5: 𛁀<span class=\"std\">（差）</span>\n6: 𛁁<span class=\"std\">（散）</span>\n7: 𛁂<span class=\"std\">（斜）</span>\n8: 𛁃<span class=\"std\">（沙）</span>\n", 
SE: "0: せ\n1: 𛁒<span class=\"std\">（世）</span>\n2: 𛁓<span class=\"std\">（世）</span>\n3: 𛁔<span class=\"std\">（世）</span>\n4: 𛁕<span class=\"std\">（勢）</span>\n5: 𛁖<span class=\"std\">（聲）</span>\n", 
SI: "0: し\n1: 𛁄<span class=\"std\">（之）</span>\n2: 𛁅<span class=\"std\">（之）</span>\n3: 𛁆<span class=\"std\">（事）</span>\n4: 𛁇<span class=\"std\">（四）</span>\n5: 𛁈<span class=\"std\">（志）</span>\n6: 𛁉<span class=\"std\">（新）</span>\n", 
SO: "0: そ\n1: 𛁗<span class=\"std\">（所）</span>\n2: 𛁘<span class=\"std\">（所）</span>\n3: 𛁙<span class=\"std\">（曾）</span>\n4: 𛁚<span class=\"std\">（曾）</span>\n5: 𛁛<span class=\"std\">（楚）</span>\n6: 𛁜<span class=\"std\">（蘇）</span>\n7: 𛁝<span class=\"std\">（處）</span>\n", 
SU: "0: す\n1: 𛁊<span class=\"std\">（受）</span>\n2: 𛁋<span class=\"std\">（壽）</span>\n3: 𛁌<span class=\"std\">（數）</span>\n4: 𛁍<span class=\"std\">（數）</span>\n5: 𛁎<span class=\"std\">（春）</span>\n6: 𛁏<span class=\"std\">（春）</span>\n7: 𛁐<span class=\"std\">（須）</span>\n8: 𛁑<span class=\"std\">（須）</span>\n", 
TA: "0: た\n1: 𛁞<span class=\"std\">（堂）</span>\n2: 𛁟<span class=\"std\">（多）</span>\n3: 𛁠<span class=\"std\">（多）</span>\n4: 𛁡<span class=\"std\">（當）</span>\n", 
TE: "0: て\n1: 𛁮<span class=\"std\">（亭）</span>\n2: 𛁯<span class=\"std\">（低）</span>\n3: 𛁰<span class=\"std\">（傳）</span>\n4: 𛁱<span class=\"std\">（天）</span>\n5: 𛁲<span class=\"std\">（天）</span>\n6: 𛁳<span class=\"std\">（天）</span>\n7: 𛁴<span class=\"std\">（帝）</span>\n8: 𛁵<span class=\"std\">（弖）</span>\n9: 𛁶<span class=\"std\">（轉）</span>\n10: 𛂎<span class=\"std\">（而）</span>\n", 
TI: "0: ち\n1: 𛁢<span class=\"std\">（千）</span>\n2: 𛁣<span class=\"std\">（地）</span>\n3: 𛁤<span class=\"std\">（智）</span>\n4: 𛁥<span class=\"std\">（知）</span>\n5: 𛁦<span class=\"std\">（知）</span>\n6: 𛁧<span class=\"std\">（致）</span>\n7: 𛁨<span class=\"std\">（遲）</span>\n", 
TO: "0: と\n1: 𛁭<span class=\"std\">（徒）</span>\n2: 𛁷<span class=\"std\">（土）</span>\n3: 𛁸<span class=\"std\">（度）</span>\n4: 𛁹<span class=\"std\">（東）</span>\n5: 𛁺<span class=\"std\">（登）</span>\n6: 𛁻<span class=\"std\">（登）</span>\n7: 𛁼<span class=\"std\">（砥）</span>\n8: 𛁽<span class=\"std\">（等）</span>\n", 
TU: "0: っ\n1: つ\n2: 𛁩<span class=\"std\">（川）</span>\n3: 𛁪<span class=\"std\">（川）</span>\n4: 𛁫<span class=\"std\">（津）</span>\n5: 𛁬<span class=\"std\">（都）</span>\n6: 𛁭<span class=\"std\">（徒）</span>\n", 
U: "0: う\n1: 𛀊<span class=\"std\">（宇）</span>\n2: 𛀋<span class=\"std\">（宇）</span>\n3: 𛀌<span class=\"std\">（憂）</span>\n4: 𛀍<span class=\"std\">（有）</span>\n5: 𛀎<span class=\"std\">（雲）</span>\n", 
VU: "0: ゔ\n", 
WA: "0: わ\n1: 𛄈<span class=\"std\">（倭）</span>\n2: 𛄉<span class=\"std\">（和）</span>\n3: 𛄊<span class=\"std\">（和）</span>\n4: 𛄋<span class=\"std\">（王）</span>\n5: 𛄌<span class=\"std\">（王）</span>\n", 
WE: "0: ゑ\n1: 𛄒<span class=\"std\">（惠）</span>\n2: 𛄓<span class=\"std\">（衞）</span>\n3: 𛄔<span class=\"std\">（衞）</span>\n4: 𛄕<span class=\"std\">（衞）</span>\n", 
WI: "0: ゐ\n1: 𛄍<span class=\"std\">（井）</span>\n2: 𛄎<span class=\"std\">（井）</span>\n3: 𛄏<span class=\"std\">（居）</span>\n4: 𛄐<span class=\"std\">（爲）</span>\n5: 𛄑<span class=\"std\">（遺）</span>\n", 
WO: "0: を\n1: 𛀅<span class=\"std\">（惡）</span>\n2: 𛄖<span class=\"std\">（乎）</span>\n3: 𛄗<span class=\"std\">（乎）</span>\n4: 𛄘<span class=\"std\">（尾）</span>\n5: 𛄙<span class=\"std\">（緒）</span>\n6: 𛄚<span class=\"std\">（越）</span>\n7: 𛄛<span class=\"std\">（遠）</span>\n8: 𛄜<span class=\"std\">（遠）</span>\n", 
YA: "0: や\n1: 𛃝<span class=\"std\">（也）</span>\n2: 𛃞<span class=\"std\">（也）</span>\n3: 𛃟<span class=\"std\">（屋）</span>\n4: 𛃠<span class=\"std\">（耶）</span>\n5: 𛃡<span class=\"std\">（耶）</span>\n6: 𛃢<span class=\"std\">（夜）</span>\n", 
YO: "0: よ\n1: 𛃢<span class=\"std\">（夜）</span>\n2: 𛃧<span class=\"std\">（代）</span>\n3: 𛃨<span class=\"std\">（余）</span>\n4: 𛃩<span class=\"std\">（與）</span>\n5: 𛃪<span class=\"std\">（與）</span>\n6: 𛃫<span class=\"std\">（與）</span>\n7: 𛃬<span class=\"std\">（餘）</span>\n", 
YU: "0: ゆ\n1: 𛃣<span class=\"std\">（游）</span>\n2: 𛃤<span class=\"std\">（由）</span>\n3: 𛃥<span class=\"std\">（由）</span>\n4: 𛃦<span class=\"std\">（遊）</span>\n", 
ZA: "0: ざ\n1: 𛀼゙\n2: 𛀽゙\n3: 𛀾゙\n4: 𛀿゙\n5: 𛁀゙\n6: 𛁁゙\n7: 𛁂゙\n8: 𛁃゙\n", 
ZE: "0: ぜ\n1: 𛁒゙\n2: 𛁓゙\n3: 𛁔゙\n4: 𛁕゙\n5: 𛁖゙\n", 
ZI: "0: じ\n1: 𛁄゙\n2: 𛁅゙\n3: 𛁆゙\n4: 𛁇゙\n5: 𛁈゙\n6: 𛁉゙\n", 
ZO: "0: ぞ\n1: 𛁗゙\n2: 𛁘゙\n3: 𛁙゙\n4: 𛁚゙\n5: 𛁛゙\n6: 𛁜゙\n7: 𛁝゙\n", 
ZU: "0: ず\n1: 𛁊゙\n2: 𛁋゙\n3: 𛁌゙\n4: 𛁍゙\n5: 𛁎゙\n6: 𛁏゙\n7: 𛁐゙\n8: 𛁑゙\n", 
};
